AddWorkspace endpoint
LT-Students/DigitalOffice-MessageService pull request #13
Opened 2020-10-25 10:40 UTC by lalagvana

2020-11-03 14:02 UTC, djino97 commented on src/MessageService.Models.Dto/AddWorkspaceRequest.cs
> +        public string Image { get; set; }
What is Image?

2020-11-29 14:20 UTC, djino97 commented on src/MessageService.Broker/MessageService.Broker.csproj
> +    <PackageReference Include="LT.DigitalOffice.Kernel" Version="1.0.11" />
fix

2020-11-29 14:34 UTC, djino97 approved these changes

2020-11-29 18:32 UTC, KanashinDmitry requested changes

2020-11-29 18:32 UTC, KanashinDmitry commented on src/MessageService.Models.Db/DbWorkspace.cs
> +        public Guid Id { get; set; }
Should we use FluentAPI here?

2020-11-29 18:32 UTC, KanashinDmitry commented on test/MessageService.Business.UnitTests/AddWorkspaceCommandTests.cs
> +                .Returns(dbWorkspace);
Should we use .Verifiable(), when using just .Verify() without arguments further?

2020-11-30 11:14 UTC, djino97 commented on src/MessageService.Models.Db/DbWorkspace.cs
> +        public Guid Id { get; set; }
Why? There are not relationship between tables

2020-11-30 11:14 UTC, djino97 commented on test/MessageService.Business.UnitTests/AddWorkspaceCommandTests.cs
> +                .Returns(dbWorkspace);
fixed

2020-11-30 12:03 UTC, MariyaSin approved these changes

2020-11-30 12:37 UTC, KanashinDmitry approved these changes

2020-11-30 12:37 UTC, merged