Rework add workspace
LT-Students/DigitalOffice-MessageService pull request #17
Opened 2021-04-05 15:56 UTC by BelehovEgor

http://outsourcing.nat.tepkom.ru:20080/redmine/issues/162
 + some parts are arranged in folders

2021-04-05 20:47 UTC, borovHokage commented on src/MessageService.Business/WorkspaceCommands/CreateWorkspaceCommand.cs
> +                    _logger.LogError(string.Join(", ", imageResponse.Message.Errors));
why you dont write LogWarning?

2021-04-05 20:49 UTC, borovHokage commented on src/MessageService.Data.Provider.MsSql.Ef/Migrations/20210104201900_ChangeWorkspace.cs
> +                        onDelete: ReferentialAction.Cascade
what does this line mean?

2021-04-05 20:59 UTC, BelehovEgor commented on src/MessageService.Data.Provider.MsSql.Ef/Migrations/20210104201900_ChangeWorkspace.cs
> +                        onDelete: ReferentialAction.Cascade
Cascade deleting

2021-04-05 21:02 UTC, BelehovEgor commented on src/MessageService.Business/WorkspaceCommands/CreateWorkspaceCommand.cs
> +                    _logger.LogError(string.Join(", ", imageResponse.Message.Errors));
I think you are right. Fixed

2021-04-07 07:15 UTC, KostinP requested changes
Almost ready

2021-04-07 07:15 UTC, KostinP commented on src/MessageService.Business/EmailTemplateCommands/AddEmailTemplateCommand.cs
> +namespace LT.DigitalOffice.MessageService.Business.EmailTemplates
Why is the folder called "EmailTemplateCommands", but the namespace says "EmailTemplates"?

2021-04-07 07:15 UTC, KostinP commented on src/MessageService.Data.Provider.MsSql.Ef/MessageServiceDbContext.cs
> +        public DbSet<DbWorkspaceAdmin> WorkspacesAdmins { get; set; }
Hm... Why?

2021-04-07 14:15 UTC, MariyaSin commented on src/MessageService.Data.Provider.MsSql.Ef/Migrations/20210104201900_ChangeWorkspace.cs
> +
Why did you can not to rename (use AlterColumn) column "image" => "ImageId" and update column type?

2021-04-07 14:29 UTC, BelehovEgor commented on src/MessageService.Data.Provider.MsSql.Ef/Migrations/20210104201900_ChangeWorkspace.cs
> +
how is this better? what will I do with the existing data?

2021-04-07 14:31 UTC, BelehovEgor commented on src/MessageService.Business/EmailTemplateCommands/AddEmailTemplateCommand.cs
> +namespace LT.DigitalOffice.MessageService.Business.EmailTemplates
fixed

2021-04-07 14:32 UTC, MariyaSin commented on src/MessageService.Data.Provider.MsSql.Ef/Migrations/20210104201900_ChangeWorkspace.cs
> +
ok

2021-04-07 14:37 UTC, BelehovEgor commented on src/MessageService.Data.Provider.MsSql.Ef/MessageServiceDbContext.cs
> +        public DbSet<DbWorkspaceAdmin> WorkspacesAdmins { get; set; }
Intresting) fixed

2021-04-07 15:52 UTC, djino97 requested changes

2021-04-07 15:52 UTC, djino97 commented on src/MessageService.Mappers/WorkspaceMappers/Interfaces/IDbWorkspaceMapper.cs
> +{
add xml docs

2021-04-07 15:52 UTC, djino97 commented on src/MessageService.Data.Provider.MsSql.Ef/Migrations/20210104201900_ChangeWorkspace.cs
> +            migrationBuilder.DropTable(DbWorkspaceAdmin.TableName);
Drop columns OwnerId, ImageId and add column Image

2021-04-07 15:52 UTC, djino97 commented on src/MessageService.Data/WorkspaceRepository.cs
> +                return _provider.Workspaces.FirstOrDefault(w => w.Id == workspace.Id).Id;
Why return existing workspace?

2021-04-07 15:52 UTC, djino97 commented on src/MessageService.Mappers/WorkspaceMappers/DbWorkspaceMapper.cs
> +                throw new BadRequestException("Value was null");
use ArgumentNullException

2021-04-07 15:52 UTC, djino97 commented on src/MessageService.Business/WorkspaceCommands/CreateWorkspaceCommand.cs
> +            var ownerId = _httpContextAccessor.HttpContext.GetUserId();
move this line into mapper

2021-04-07 15:52 UTC, djino97 commented on src/MessageService.Business/WorkspaceCommands/CreateWorkspaceCommand.cs
> +            var imageId = CreateImageRequest(workspace.Image);
AddImageContent

2021-04-07 15:52 UTC, djino97 commented on src/MessageService.Models.Db/DbWorkspace.cs
> +                .IsRequired();
default required, it is structure

2021-04-07 15:52 UTC, djino97 commented on src/MessageService.Models.Db/DbWorkspace.cs
> +                .IsRequired();
default required

2021-04-07 16:05 UTC, BelehovEgor commented on src/MessageService.Business/WorkspaceCommands/CreateWorkspaceCommand.cs
> +        private Guid? CreateImageRequest(string image)
fixed

2021-04-07 16:05 UTC, BelehovEgor commented on src/MessageService/Controllers/WorkspaceController.cs
> +        public Guid CreateWorkspace(
fixed

2021-04-07 16:17 UTC, BelehovEgor commented on src/MessageService.Data.Provider.MsSql.Ef/Migrations/20210104201900_ChangeWorkspace.cs
> +            migrationBuilder.DropTable(DbWorkspaceAdmin.TableName);
fixed

2021-04-07 16:27 UTC, BelehovEgor commented on src/MessageService.Data/WorkspaceRepository.cs
> +                return _provider.Workspaces.FirstOrDefault(w => w.Id == workspace.Id).Id;
shouldn't this method return the Id of the workspace with these parameters, i.e. if it already exists, we will return the existing Id. But here I really don't know how to do better

2021-04-07 16:29 UTC, BelehovEgor commented on src/MessageService.Mappers/WorkspaceMappers/DbWorkspaceMapper.cs
> +                throw new BadRequestException("Value was null");
fixed

2021-04-07 16:31 UTC, BelehovEgor commented on src/MessageService.Business/WorkspaceCommands/CreateWorkspaceCommand.cs
> +            var ownerId = _httpContextAccessor.HttpContext.GetUserId();
These parts are taken out specifically from the mapper, as otherwise, they will violate the single responsibility

2021-04-07 16:32 UTC, BelehovEgor commented on src/MessageService.Business/WorkspaceCommands/CreateWorkspaceCommand.cs
> +            var imageId = CreateImageRequest(workspace.Image);
fixed

2021-04-07 16:33 UTC, BelehovEgor commented on src/MessageService.Models.Db/DbWorkspace.cs
> +                .IsRequired();
fixed

2021-04-07 16:33 UTC, BelehovEgor commented on src/MessageService.Models.Db/DbWorkspace.cs
> +                .IsRequired();
fixed

2021-04-07 17:20 UTC, BelehovEgor commented on src/MessageService.Data/WorkspaceRepository.cs
> +                return _provider.Workspaces.FirstOrDefault(w => w.Id == workspace.Id).Id;
removed

2021-04-07 18:25 UTC, KostinP approved these changes

2021-04-07 18:27 UTC, TIove commented on test/MessageService.Business.UnitTests/CreateWorkspaceCommandTests.cs
> +            Assert.That(_command.Execute(_workspace), Is.EqualTo(_workspaceId));
I think AreEqual would be better here and in other places

2021-04-07 18:36 UTC, TIove commented on src/MessageService.Business/WorkspaceCommands/CreateWorkspaceCommand.cs
> +                var imageResponse = _requestClient.GetResponse<IOperationResult<IAddImageResponse>>(imageRequest).Result;
Mb you should add timeout ms: 500 like in UserService

2021-04-07 19:32 UTC, BelehovEgor commented on test/MessageService.Business.UnitTests/CreateWorkspaceCommandTests.cs
> +            Assert.That(_command.Execute(_workspace), Is.EqualTo(_workspaceId));
fixed

2021-04-07 19:33 UTC, BelehovEgor commented on src/MessageService.Business/WorkspaceCommands/CreateWorkspaceCommand.cs
> +                var imageResponse = _requestClient.GetResponse<IOperationResult<IAddImageResponse>>(imageRequest).Result;
the attribute with timeout will appear in the future, it is not my task

2021-04-07 19:42 UTC, TIove approved these changes

2021-04-07 23:47 UTC, djino97 requested changes

2021-04-07 23:47 UTC, djino97 commented on src/MessageService.Data.Provider/IDataProvider.cs
> +        DbSet<DbWorkspaceAdmin> Admins { get; set; }
WorkspaceAdmins

2021-04-07 23:47 UTC, djino97 commented on src/MessageService.Models.Broker/Responses/IAddImageResponse.cs
> +        public Guid? Id { get; }
public?

2021-04-07 23:47 UTC, djino97 commented on src/MessageService.Models.Db/DbWorkspace.cs
>          public bool IsActive { get; set; }
write guid near guid,  string near string

2021-04-07 23:47 UTC, djino97 commented on test/MessageService.Business.UnitTests/CreateWorkspaceCommandTests.cs
> +            _requestBrokerMock = new Mock<IRequestClient<IAddImageRequest>>();
the second time you create instance

2021-04-08 04:48 UTC, BelehovEgor commented on test/MessageService.Business.UnitTests/CreateWorkspaceCommandTests.cs
> +            _requestBrokerMock = new Mock<IRequestClient<IAddImageRequest>>();
fixed

2021-04-08 04:48 UTC, BelehovEgor commented on src/MessageService.Models.Db/DbWorkspace.cs
>          public bool IsActive { get; set; }
fixed

2021-04-08 04:48 UTC, BelehovEgor commented on src/MessageService.Models.Broker/Responses/IAddImageResponse.cs
> +        public Guid? Id { get; }
removed

2021-04-08 04:48 UTC, BelehovEgor commented on src/MessageService.Data.Provider/IDataProvider.cs
> +        DbSet<DbWorkspaceAdmin> Admins { get; set; }
renamed

2021-04-08 09:03 UTC, djino97 approved these changes

2021-04-08 11:40 UTC, merged