Add RemoveWorkspace endpoint
LT-Students/DigitalOffice-MessageService pull request #18
Opened 2021-04-08 21:32 UTC by BelehovEgor

http://outsourcing.nat.tepkom.ru:20080/redmine/issues/163

2021-04-08 21:45 UTC, KostinP commented on src/MessageService.Data/Interfaces/IWorkspaceRepository.cs
> +        bool SwitchActiveStatus(Guid workspaceId, bool status);
Why not EditWorkspace?

2021-04-09 04:39 UTC, BelehovEgor commented on src/MessageService.Data/Interfaces/IWorkspaceRepository.cs
> +        bool SwitchActiveStatus(Guid workspaceId, bool status);
What do you want? rename method?

2021-04-09 06:00 UTC, BelehovEgor commented on src/MessageService.Data/Interfaces/IWorkspaceRepository.cs
> +        bool SwitchActiveStatus(Guid workspaceId, bool status);
to be honest, you can see this in the User service, which was written by Spartak

2021-04-09 08:33 UTC, borovHokage commented on test/MessageService.Business.UnitTests/RemoveWorkspaceCommandTest.cs
> +            ClientRequestUp(_ownerId);
here we call ownerId? i dont see this construction earlier

2021-04-09 08:52 UTC, BelehovEgor commented on test/MessageService.Business.UnitTests/RemoveWorkspaceCommandTest.cs
> +            ClientRequestUp(_ownerId);
What do you mean? I need user id in http context and i have private method for this, which put id to context

2021-04-10 14:32 UTC, KostinP approved these changes

2021-04-10 14:32 UTC, KostinP commented on src/MessageService.Business/WorkspaceCommands/RemoveWorkspaceCommand.cs
> +
Extra empty line

2021-04-10 14:32 UTC, KostinP commented on test/MessageService.Business.UnitTests/RemoveWorkspaceCommandTest.cs
> +
Extra empty line

2021-04-10 14:32 UTC, KostinP commented on test/MessageService.Business.UnitTests/RemoveWorkspaceCommandTest.cs
> +        private void ClientRequestUp(Guid id)
Rename

2021-04-10 14:32 UTC, KostinP commented on test/MessageService.Data.UnitTests/UserRepositoryTests.cs
> +        public void CreateMemoryDb()
InMemoryDb

2021-04-10 14:32 UTC, KostinP commented on test/MessageService.Business.UnitTests/RemoveWorkspaceCommandTest.cs
> +    class RemoveWorkspaceCommandTest
Tests

2021-04-11 00:14 UTC, djino97 requested changes

2021-04-11 00:14 UTC, djino97 commented on src/MessageService.Data/UserRepository.cs
> +        }
most likely we do not need a separate separate repository for admins, since they can be obtained through the workspace.

2021-04-11 05:29 UTC, BelehovEgor commented on src/MessageService.Data/UserRepository.cs
> +        }
In future we will add/remove users to workspace and channels. I think, we need it.

2021-04-11 18:29 UTC, KostinP approved these changes

2021-04-12 08:49 UTC, djino97 approved these changes

2021-04-12 13:43 UTC, TIove commented on src/MessageService.Data/WorkspaceRepository.cs
> +            DbWorkspace dbWorkspace = _provider.Workspaces.FirstOrDefault(w => w.Id == workspaceId);
I dunno about readable, but u can set ?? after this and throw an exception. It would be look more laconically

2021-04-12 13:53 UTC, TIove commented on test/MessageService.Business.UnitTests/RemoveWorkspaceCommandTests.cs
> +            var i = _dbWorkspaceAdmin.Id;
What is it?

2021-04-12 13:56 UTC, BelehovEgor commented on test/MessageService.Business.UnitTests/RemoveWorkspaceCommandTests.cs
> +            var i = _dbWorkspaceAdmin.Id;
fixed

2021-04-12 13:57 UTC, TIove approved these changes

2021-04-12 17:15 UTC, 24eeeee approved these changes
Kinda cringe branch name bruh

2021-04-12 17:34 UTC, merged