Add email template parsing logic
LT-Students/DigitalOffice-MessageService pull request #19
Opened 2021-04-09 16:35 UTC by djino97

http://outsourcing.nat.tepkom.ru:20080/redmine/issues/305

2021-04-10 21:35 UTC, BelehovEgor commented on src/MessageService.Mappers/EmailMappers/EmailTemplateTextMapper.cs
> +    public class EmailTemplateTextMapper : IMapper<EmailTemplateTextInfo, DbEmailTemplateText>
We name mappers by the entity we are converting them to

2021-04-10 21:35 UTC, BelehovEgor commented on src/MessageService.Mappers/EmailMappers/EmailTemplateMapper.cs
> +    public class EmailTemplateMapper : IMapper<EmailTemplateRequest, DbEmailTemplate>,
why do we implement two interfaces instead of splitting them into two classes

2021-04-11 17:19 UTC, djino97 commented on src/MessageService.Mappers/EmailMappers/EmailTemplateTextMapper.cs
> +    public class EmailTemplateTextMapper : IMapper<EmailTemplateTextInfo, DbEmailTemplateText>
after this pull request, a complete refactoring of this service will be carried out

2021-04-11 17:22 UTC, djino97 commented on src/MessageService.Mappers/EmailMappers/EmailTemplateMapper.cs
> +    public class EmailTemplateMapper : IMapper<EmailTemplateRequest, DbEmailTemplate>,
After this pull request, a complete refactoring of this service will be carried out. I will fix this in refactoring.

2021-04-11 19:28 UTC, BelehovEgor requested changes

2021-04-11 19:28 UTC, BelehovEgor commented on src/MessageService.Broker/Consumers/SendEmailConsumer.cs
> +            catch (Exception ex)
here try to find the type of exc that the Send method can throw, I think this method has a narrower exception

2021-04-11 19:28 UTC, BelehovEgor commented on src/MessageService.Broker/Consumers/SendEmailConsumer.cs
> +            DbEmailTemplate dbEmailTemplate;
do one-line initialization

2021-04-11 19:28 UTC, BelehovEgor commented on src/MessageService.Broker/Consumers/EmailTemplateTagsConsumer.cs
> +        private DbEmailTemplateText GetDbEmailTemplateText(IGetEmailTemplateTagsRequest request)
replace this PRIVATE method above the public methods, since you adhere to this code style

2021-04-11 19:28 UTC, BelehovEgor commented on src/MessageService.Validation/AddEmailTemplateValidator.cs
> +                    ett.RuleFor(ett => ett.Language)
2 letters?

2021-04-11 20:51 UTC, djino97 commented on src/MessageService.Broker/Consumers/SendEmailConsumer.cs
> +            catch (Exception ex)
fixed

2021-04-11 20:52 UTC, djino97 commented on src/MessageService.Broker/Consumers/SendEmailConsumer.cs
> +            DbEmailTemplate dbEmailTemplate;
fixed

2021-04-11 20:52 UTC, djino97 commented on src/MessageService.Broker/Consumers/EmailTemplateTagsConsumer.cs
> +        private DbEmailTemplateText GetDbEmailTemplateText(IGetEmailTemplateTagsRequest request)
fixed

2021-04-11 20:52 UTC, djino97 commented on src/MessageService.Validation/AddEmailTemplateValidator.cs
> +                    ett.RuleFor(ett => ett.Language)
fixed

2021-04-11 20:56 UTC, BelehovEgor approved these changes

2021-04-12 09:28 UTC, KostinP requested changes
First review (style)

2021-04-12 09:28 UTC, KostinP commented on src/MessageService.Broker/Consumers/EmailTemplateTagsConsumer.cs
> +                throw new NotFoundException(messageTemp);
Remove `_logger.LogWarning(messageTemp)`

2021-04-12 09:28 UTC, KostinP commented on src/MessageService.Broker/Consumers/SendEmailConsumer.cs
> +                throw new NotFoundException(messageTemp);
Remove `_logger.LogWarning(messageTemp)`

2021-04-12 09:28 UTC, KostinP commented on src/MessageService.Broker/Consumers/SendEmailConsumer.cs
> +            }
foreach

2021-04-12 09:28 UTC, KostinP commented on src/MessageService.Validation/AddEmailTemplateValidator.cs
> +                    .NotNull();
Remove extra spaces

2021-04-12 09:28 UTC, KostinP commented on test/MessageService.Mappers.UnitTests/EmailTemplateMapperTests.cs
> +                dbEmailTemplateText.Language = templateText.Language;
```
new DbEmailTemplateText
{
    Subject = templateText.Subject;
    Text = templateText.Text;
    Language = templateText.Language;
}
```

2021-04-12 09:28 UTC, KostinP commented on test/MessageService.Business.UnitTests/EditEmailTemplateCommandTests.cs
> +                dbEmailTemplateText.Language = dbEmailTemplateText.Language;
```
new DbEmailTemplateText
{
    Subject = templateText.Subject;
    Text = templateText.Text;
    Language = dbEmailTemplateText.Language;
}
```

2021-04-12 09:28 UTC, KostinP commented on test/MessageService.Business.UnitTests/EditEmailTemplateCommandTests.cs
> +            newDbEmailTemplate.IsActive = dbEmailTemplate.IsActive;
```
new
{
    Id = emailTemplateId;
    CreatedAt = dbEmailTemplate.CreatedAt;
    Name = newEmailTemplate.Name;
    Type = (int)newEmailTemplate.Type;
    AuthorId = dbEmailTemplate.AuthorId;
    IsActive = dbEmailTemplate.IsActive;
}
```

2021-04-12 09:28 UTC, KostinP commented on test/MessageService.Business.UnitTests/AddEmailTemplateCommandTests.cs
> +                dbEmailTemplateText.Language = dbEmailTemplateText.Language;
```
new DbEmailTemplateText
{
    Subject = templateText.Subject;
    Text = templateText.Text;
    Language = dbEmailTemplateText.Language;
}
```

2021-04-12 10:55 UTC, djino97 commented on src/MessageService.Broker/Consumers/EmailTemplateTagsConsumer.cs
> +                throw new NotFoundException(messageTemp);
Why?

2021-04-12 10:56 UTC, djino97 commented on src/MessageService.Broker/Consumers/SendEmailConsumer.cs
> +            }
why?

2021-04-12 10:58 UTC, djino97 commented on src/MessageService.Broker/Consumers/SendEmailConsumer.cs
> +                throw new NotFoundException(messageTemp);
Why?

2021-04-12 11:14 UTC, KostinP commented on src/MessageService.Broker/Consumers/EmailTemplateTagsConsumer.cs
> +                throw new NotFoundException(messageTemp);
When the error handler fires, it logs information about the error

2021-04-12 11:14 UTC, KostinP commented on src/MessageService.Broker/Consumers/SendEmailConsumer.cs
> +                throw new NotFoundException(messageTemp);
When the error handler fires, it logs information about the error

2021-04-12 12:27 UTC, djino97 commented on src/MessageService.Broker/Consumers/SendEmailConsumer.cs
> +                throw new NotFoundException(messageTemp);
How do we know on the other side that in consumer throw exception?

2021-04-12 13:07 UTC, borovHokage commented on test/MessageService.Data.UnitTests/EmailTemplateRepositoryTests.cs
> +            Assert.Throws<NotFoundException>(() => repository.DisableEmailTemplate(Guid.Empty));
can we use null instead of Guid.Empty?

2021-04-12 13:37 UTC, djino97 commented on test/MessageService.Data.UnitTests/EmailTemplateRepositoryTests.cs
> +            Assert.Throws<NotFoundException>(() => repository.DisableEmailTemplate(Guid.Empty));
No, so as Guid is structure, then guid may be empty "00000000-0000-0000-0000-000000000000". And so if we made guid?, then we can made use null

2021-04-12 14:07 UTC, borovHokage approved these changes

2021-04-12 14:23 UTC, djino97 commented on src/MessageService.Validation/AddEmailTemplateValidator.cs
> +                    .NotNull();
Why?

2021-04-12 15:30 UTC, djino97 commented on src/MessageService.Validation/AddEmailTemplateValidator.cs
> +                    .NotNull();
fixed

2021-04-12 15:34 UTC, djino97 commented on test/MessageService.Mappers.UnitTests/EmailTemplateMapperTests.cs
> +                dbEmailTemplateText.Language = templateText.Language;
fixed

2021-04-12 15:35 UTC, djino97 commented on test/MessageService.Business.UnitTests/EditEmailTemplateCommandTests.cs
> +            newDbEmailTemplate.IsActive = dbEmailTemplate.IsActive;
fixed

2021-04-12 15:35 UTC, djino97 commented on test/MessageService.Business.UnitTests/AddEmailTemplateCommandTests.cs
> +                dbEmailTemplateText.Language = dbEmailTemplateText.Language;
fixed

2021-04-12 15:35 UTC, djino97 commented on test/MessageService.Business.UnitTests/EditEmailTemplateCommandTests.cs
> +                dbEmailTemplateText.Language = dbEmailTemplateText.Language;
fixed

2021-04-12 16:59 UTC, 24eeeee commented on src/MessageService.Business/EmailTemplateCommands/EditEmailTemplateCommand.cs
> +            [FromServices] IMapper<EditEmailTemplateRequest, DbEmailTemplate> mapperEmailTemplate)
Would that work without **[FromServices]** ?

2021-04-12 17:21 UTC, 24eeeee approved these changes

2021-04-12 19:39 UTC, djino97 commented on src/MessageService.Business/EmailTemplateCommands/EditEmailTemplateCommand.cs
> +            [FromServices] IMapper<EditEmailTemplateRequest, DbEmailTemplate> mapperEmailTemplate)
yes, but this will  remove in future

2021-04-12 23:51 UTC, KostinP approved these changes

2021-04-13 07:04 UTC, merged