update_healthcheck
LT-Students/DigitalOffice-MessageService pull request #21
Opened 2021-04-14 20:22 UTC by borovHokage

http://outsourcing.nat.tepkom.ru:20080/redmine/issues/248
Remove UseHealthChecks()
Map healthcheck endpoint to '/{serviceID}/hc'
Add RabbitMQ healthcheck Add SQL Server healthcheck
Rework healthcheck endpoint response
create pull request & fix bugs

2021-04-14 20:29 UTC, KostinP approved these changes
Update appsettings.json

2021-04-14 20:29 UTC, KostinP commented on src/MessageService/Startup.cs
> +            //services.AddKernelExtensions();
Remove

2021-04-14 20:30 UTC, KostinP requested changes
Mistake

2021-04-14 20:32 UTC, BelehovEgor requested changes

2021-04-14 20:32 UTC, BelehovEgor commented on src/MessageService/Startup.cs
> +            //services.AddKernelExtensions();
comment???

2021-04-14 20:32 UTC, BelehovEgor commented on src/MessageService/Startup.cs
> +                .AddHealthChecks()
you have AddHealthChecks above, delete

2021-04-14 20:32 UTC, KostinP requested changes

2021-04-14 20:32 UTC, KostinP commented on Common.Configurations.targets
> +    <PackageReference Include="LT.DigitalOffice.UnitTestKernel" Version="1.0.2" />
1.0.4

2021-04-14 20:32 UTC, KostinP commented on Common.Configurations.targets
> +    <PackageReference Include="LT.DigitalOffice.Kernel" Version="1.1.21" />
1.1.22

2021-04-15 09:37 UTC, borovHokage commented on src/MessageService/Startup.cs
> +            //services.AddKernelExtensions();
done

2021-04-15 09:37 UTC, borovHokage commented on src/MessageService/Startup.cs
> +            //services.AddKernelExtensions();
done

2021-04-15 09:37 UTC, borovHokage commented on src/MessageService/Startup.cs
> +                .AddHealthChecks()
done

2021-04-15 12:42 UTC, 24eeeee approved these changes

2021-04-15 12:44 UTC, BelehovEgor approved these changes

2021-04-15 12:46 UTC, TIove commented on Common.Configurations.targets
> +    <PackageReference Include="LT.DigitalOffice.UnitTestKernel" Version="1.0.2" />
Up to date version is 1.0.4

2021-04-15 12:46 UTC, KostinP approved these changes

2021-04-15 12:47 UTC, BelehovEgor commented on Common.Configurations.targets
> +    <PackageReference Include="LT.DigitalOffice.UnitTestKernel" Version="1.0.2" />
it will be in refactoring, not now

2021-04-15 12:49 UTC, TIove approved these changes

2021-04-15 12:56 UTC, merged