add smpt configuration read from Environment
LT-Students/DigitalOffice-MessageService pull request #22
Opened 2021-04-17 12:05 UTC by borovHokage

http://outsourcing.nat.tepkom.ru:20080/redmine/issues/254

Task #407: Add logic to read smtp configuration from Environment.

2021-04-17 12:07 UTC, KostinP requested changes

2021-04-17 12:07 UTC, KostinP commented on src/MessageService/Startup.cs
> +            }
You just got the variables, what's next?

2021-04-17 12:09 UTC, KostinP requested changes

2021-04-17 12:09 UTC, KostinP commented on src/MessageService/Startup.cs
> +                smptHost = Configuration.GetConnectionString("Host");
It works?

2021-04-17 23:41 UTC, KostinP requested changes

2021-04-17 23:41 UTC, KostinP commented on src/MessageService/Startup.cs
> +                smtpCredentialsOptions[nameof(SmtpCredentialsOptions.Host)]  = smtpHost;
Extra space 
...{space}{space}{=}...

2021-04-17 23:41 UTC, KostinP commented on src/MessageService/Startup.cs
> +
Double setup Configure<SmtpCredentialsOptions> (line 78, line 116)

2021-04-18 05:28 UTC, borovHokage commented on src/MessageService/Startup.cs
> +
fixed

2021-04-18 05:28 UTC, borovHokage commented on src/MessageService/Startup.cs
> +                smtpCredentialsOptions[nameof(SmtpCredentialsOptions.Host)]  = smtpHost;
fixed

2021-04-18 05:29 UTC, borovHokage commented on src/MessageService/Startup.cs
> +            }
fixed

2021-04-18 05:29 UTC, borovHokage commented on src/MessageService/Startup.cs
> +                smptHost = Configuration.GetConnectionString("Host");
fixed

2021-04-18 07:18 UTC, KostinP requested changes

2021-04-18 07:18 UTC, KostinP commented on src/MessageService/Startup.cs
>              services.Configure<SmtpCredentialsOptions>(smtpCredentialsOptions);
What do you think the `Configure` method does?

2021-04-18 09:19 UTC, KostinP requested changes

2021-04-18 09:19 UTC, KostinP commented on src/MessageService/Startup.cs
> +            if (string.IsNullOrEmpty(smtpHost))
!

2021-04-18 09:21 UTC, KostinP approved these changes

2021-04-18 09:30 UTC, djino97 approved these changes

2021-04-18 09:30 UTC, djino97 commented on src/MessageService/Startup.cs
> +            }
This can move in method other (reduce code)

2021-04-18 17:04 UTC, borovHokage commented on src/MessageService/Startup.cs
>              services.Configure<SmtpCredentialsOptions>(smtpCredentialsOptions);
fixed

2021-04-18 17:04 UTC, borovHokage commented on src/MessageService/Startup.cs
> +            if (string.IsNullOrEmpty(smtpHost))
fixed

2021-04-18 17:17 UTC, BelehovEgor approved these changes

2021-04-19 09:44 UTC, TIove approved these changes

2021-04-19 10:40 UTC, merged