Remove email template logic
LT-Students/DigitalOffice-MessageService pull request #8
Opened 2020-09-21 18:02 UTC by lalagvana

2020-10-01 22:59 UTC, djino97 commented on src/MessageService.Business/Interfaces/IRemoveEmailTemplateCommand.cs
> +        void Execute(Guid emailTemplateId, Guid requestingUserId);
add description for requestingUserId

2020-10-01 22:59 UTC, djino97 commented on src/MessageService.Business/RemoveEmailTemplateCommand.cs
> +            if (!isAcces)
Add empty line

2020-10-01 22:59 UTC, djino97 commented on src/MessageService.Business/RemoveEmailTemplateCommand.cs
> +            int numberRight = 3;
move in field of class

2020-10-01 22:59 UTC, djino97 commented on src/MessageService.Data/EmailTemplateRepository.cs
> +        {
DisableEmailTemplate

2020-10-01 22:59 UTC, djino97 commented on src/MessageService.Business/RemoveEmailTemplateCommand.cs
> +    {
RemoveEmailTemplateCommand

2020-10-01 22:59 UTC, djino97 commented on test/MessageService.Business.UnitTests/RemoveEmailTemplateCommandTests.cs
> +            command = new RemoveEmailTemplateCommand(repositoryMock.Object, accessValidatorMock.Object);
This can also be transferred to OneTimeSetUp

2020-10-01 22:59 UTC, djino97 commented on test/MessageService.Data.UnitTests/EmailTemplateRepositoryTests.cs
> +        {
May be use `when `then `if `? (convention)

2020-10-02 07:41 UTC, lalagvana commented on src/MessageService.Business/RemoveEmailTemplateCommand.cs
> +    {
?

2020-10-02 10:01 UTC, djino97 commented on src/MessageService.Business/RemoveEmailTemplateCommand.cs
> +    {
Sorry, DisableEmailTemplateCommand

2020-10-02 10:10 UTC, djino97 commented on src/MessageService.Data.Provider.MsSql.Ef/MessageService.Data.Provider.MsSql.Ef.csproj
> +
Remove

2020-10-02 10:10 UTC, djino97 commented on src/MessageService.Data/EmailTemplateRepository.cs
> +
Maybe use FirstOrDefault?

2020-10-02 10:10 UTC, djino97 commented on src/MessageService.Data/MessageService.Data.csproj
> +
Remove

2020-10-02 10:34 UTC, lalagvana commented on src/MessageService.Data/EmailTemplateRepository.cs
> +
Why is it better to use it instead of Find?

2020-10-02 11:22 UTC, djino97 commented on src/MessageService.Data/EmailTemplateRepository.cs
> +
FirstOrDefault() method always executes a query on the database. https://arwsoftware.wordpress.com/2017/02/04/entity-framework-find-vs-firstordefault/

2020-10-06 12:37 UTC, djino97 approved these changes

2020-10-09 18:52 UTC, DarkFelas requested changes

2020-10-09 18:52 UTC, DarkFelas commented on src/MessageService.Business/DisableEmailTemplateCommand.cs
> +            if (!isAcces)
isAcces**s**

2020-10-09 18:52 UTC, DarkFelas commented on src/MessageService.Business/MessageService.Business.csproj
> +    <PackageReference Include="LT.DigitalOffice.Kernel" Version="1.0.6" />
1.0.9

2020-10-09 18:53 UTC, DarkFelas approved these changes

2020-10-09 19:31 UTC, merged